import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mahedi H Sharif || Full Stack Web Developer",
  description: "Generated by Mahedi H Sharif",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="2xl:px-[20rem] px-10">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
